services:
  - type: web
    name: workers-production-system
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true
